spring:
  application:
    name: movie-service
  config:
    import: optional:configserver:http://localhost:8888

    # Configuración de RabbitMQ
    spring:
      rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

    # Nombre de la cola para recibir mensajes
    movie:
      queue: movie-queue

# Configuración de MongoDB
  spring:
  data:
  mongodb:
  uri: mongodb://localhost:27017/movie_database

