spring:
  application:
    name: movie-service
  config:
    import: optional:configserver:http://localhost:8888

    # Configuración de RabbitMQ
    spring.rabbitmq.host=localhost
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=guest
    spring.rabbitmq.password=guest

    # Nombre de la cola para recibir mensajes
    movie.queue=movie-queue

